name = "Unicode2LaTeX"
uuid = "a6a4b4a1-58ae-5f2f-bbf9-c7004aa6538b"
authors = ["Pontus Stenetorp <pontus@stenetorp.se>"]
version = "1.2.0"

[compat]
julia = "1.0, 1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
